ALTER TABLE blackouts ADD COLUMN IF NOT EXISTS environment_glob TEXT DEFAULT NULL;
ALTER TABLE blackouts ADD COLUMN IF NOT EXISTS host_glob TEXT DEFAULT NULL;
ALTER TABLE blackouts ADD COLUMN IF NOT EXISTS service_glob TEXT DEFAULT NULL;
