module Application.Service.Push
( VapidKeys (..)
, loadVapidKeys
, vapidPublicKey
, sendPush
, PushResult (..)
, signVapidJwt
, encryptPayload
, b64urlEncode
, b64urlDecode
, pointFromBytes
, pointToBytes
, os2ip
, i2osp
) where

import IHP.Prelude hiding (first)
import Generated.Types (PushSubscription, endpoint, p256dh, auth)
import Data.Aeson (object, (.=))
import Data.Aeson.Types (parseMaybe)
import qualified Data.Aeson as Aeson
import qualified Data.ByteString as BS
import Data.ByteString (ByteString)
import qualified Data.ByteString.Lazy as BL
import qualified Data.ByteString.Base64.URL as B64URL
import Data.Bits (shiftR, shiftL, (.&.))
import Data.ByteArray (convert)
import "cryptonite" Crypto.PubKey.ECC.Types (CurveName (SEC_p256r1), getCurveByName, Point (..))
import "cryptonite" Crypto.PubKey.ECC.DH (generatePrivate, calculatePublic, getShared)
import "cryptonite" Crypto.PubKey.ECC.ECDSA (PrivateKey (..), Signature (..), sign)
import "cryptonite" Crypto.Hash (SHA256 (..))
import qualified "cryptonite" Crypto.KDF.HKDF as HKDF
import "cryptonite" Crypto.Cipher.AES (AES128)
import "cryptonite" Crypto.Cipher.Types (cipherInit, aeadInit, AEADMode (AEAD_GCM), aeadSimpleEncrypt, AuthTag (..))
import "cryptonite" Crypto.Error (CryptoFailable (..))
import "cryptonite" Crypto.Random (getRandomBytes)
import qualified Data.Text as Text
import Data.Time.Clock.POSIX (utcTimeToPOSIXSeconds)
import qualified Network.HTTP.Client as HTTP
import qualified Network.HTTP.Client.TLS as TLS
import Network.HTTP.Types (status201, status202, status404, status410)
import System.IO.Unsafe (unsafePerformIO)
import System.Environment (lookupEnv)

-- Hand-rolled VAPID (RFC 8292) + Web Push payload encryption (RFC 8291,
-- aes128gcm content coding). The Hackage `web-push` library (0.3, 2020)
-- implements only the pre-RFC draft encoding which modern push services
-- reject, hence this implementation (milestone_1.md §12/§13).

data VapidKeys = VapidKeys
    { vapidPublicKeyB64Url :: Text
    , vapidPrivateScalar :: Integer
    , vapidSubject :: Text
    }

data PushResult = PushDelivered | PushSubscriptionGone | PushFailed Text
    deriving (Eq, Show)

-- | Reads keys from $HALEMANS_VAPID_JSON (generated by halemans-ensure-tokens).
loadVapidKeys :: IO (Maybe VapidKeys)
loadVapidKeys = do
    path <- lookupEnv "HALEMANS_VAPID_JSON"
    subject <- fromMaybe "mailto:admin@halemans.local" . fmap cs <$> lookupEnv "HALEMANS_VAPID_SUBJECT"
    case path of
        Nothing -> pure Nothing
        Just path -> do
            contents <- BS.readFile path
            case Aeson.decode (BL.fromStrict contents) of
                Nothing -> pure Nothing
                Just value -> do
                    let parsed = parseMaybe parser value
                        parser = Aeson.withObject "vapid" \o -> do
                            pub <- o Aeson..: "publicKey"
                            priv <- o Aeson..: "privateKey"
                            pure (pub, priv)
                    case parsed of
                        Just (pub, priv) -> Just <$> pure VapidKeys
                            { vapidPublicKeyB64Url = pub
                            , vapidPrivateScalar = os2ip (b64urlDecode priv)
                            , vapidSubject = subject
                            }
                        Nothing -> pure Nothing

vapidPublicKey :: IO (Maybe Text)
vapidPublicKey = fmap vapidPublicKeyB64Url <$> loadVapidKeys

manager :: HTTP.Manager
manager = unsafePerformIO (HTTP.newManager TLS.tlsManagerSettings)
{-# NOINLINE manager #-}

sendPush :: VapidKeys -> PushSubscription -> BL.ByteString -> IO PushResult
sendPush keys subscription payload = do
    let endpoint = subscription.endpoint
    encrypted <- encryptPayload subscription payload
    case encrypted of
        Left err -> pure (PushFailed err)
        Right body -> do
            jwt <- signVapidJwt keys endpoint
            request <- HTTP.parseRequest (cs endpoint)
            let request' = request
                    { HTTP.method = "POST"
                    , HTTP.requestBody = HTTP.RequestBodyLBS (BL.fromStrict body)
                    , HTTP.requestHeaders =
                        [ ("Authorization", cs jwt)
                        , ("TTL", "86400")
                        , ("Content-Encoding", "aes128gcm")
                        , ("Content-Type", "application/octet-stream")
                        ]
                    }
            response <- HTTP.httpLbs request' manager
            let status = HTTP.responseStatus response
            pure $ if
                | status == status201 || status == status202 -> PushDelivered
                | status == status404 || status == status410 -> PushSubscriptionGone
                | otherwise -> PushFailed (tshow status)

-- RFC 8292: ES256-signed JWT with aud = push service origin.
signVapidJwt :: VapidKeys -> Text -> IO Text
signVapidJwt keys endpoint = do
    now <- getCurrentTime
    let header = b64urlEncode (BL.toStrict (Aeson.encode (object ["typ" .= ("JWT" :: Text), "alg" .= ("ES256" :: Text)])))
        claims = b64urlEncode (BL.toStrict (Aeson.encode (object
            [ "aud" .= originOf endpoint
            , "exp" .= (floor (utcTimeToPOSIXSeconds (addUTCTime 43200 now)) :: Integer)
            , "sub" .= keys.vapidSubject
            ])))
        signingInput = header <> "." <> claims
    signature <- sign privateKey SHA256 (cs signingInput :: ByteString)
    let signatureBytes = i2osp 32 signature.sign_r <> i2osp 32 signature.sign_s
    pure (signingInput <> "." <> b64urlEncode signatureBytes)
    where
        privateKey = PrivateKey { private_curve = curve, private_d = keys.vapidPrivateScalar }
        curve = getCurveByName SEC_p256r1

originOf :: Text -> Text
originOf endpoint =
    let afterScheme = fromMaybe endpoint (Text.stripPrefix "https://" endpoint <|> Text.stripPrefix "http://" endpoint)
        hostPort = Text.takeWhile (/= '/') afterScheme
        scheme = if "https://" `Text.isPrefixOf` endpoint then "https://" else "http://"
    in scheme <> hostPort

-- RFC 8291 payload encryption, single record, aes128gcm (RFC 8188) body.
encryptPayload :: PushSubscription -> BL.ByteString -> IO (Either Text ByteString)
encryptPayload subscription payload = do
    let curve = getCurveByName SEC_p256r1
    let subscriberPublicBytes = b64urlDecode subscription.p256dh
        authSecret = b64urlDecode subscription.auth
    case pointFromBytes subscriberPublicBytes of
        Nothing -> pure (Left "invalid p256dh key")
        Just subscriberPublic -> do
            serverPrivate <- generatePrivate curve
            let serverPublic = calculatePublic curve serverPrivate
                sharedSecret = convert (getShared curve serverPrivate subscriberPublic) :: ByteString
                keyInfo = "WebPush: info" <> BS.singleton 0 <> subscriberPublicBytes <> pointToBytes serverPublic
                prkKey = HKDF.extract authSecret sharedSecret :: HKDF.PRK SHA256
                ikm = HKDF.expand prkKey keyInfo 32 :: ByteString
            salt <- randomBytes 16
            let prk = HKDF.extract salt ikm :: HKDF.PRK SHA256
                cek = HKDF.expand prk ("Content-Encoding: aes128gcm" <> BS.singleton 0) 16 :: ByteString
                nonce = HKDF.expand prk ("Content-Encoding: nonce" <> BS.singleton 0) 12 :: ByteString
            case cipherInit cek of
                CryptoFailed _ -> pure (Left "cipher init failed")
                CryptoPassed (cipher :: AES128) -> do
                    let aeadInitResult = aeadInit AEAD_GCM cipher nonce
                    case aeadInitResult of
                        CryptoFailed _ -> pure (Left "aead init failed")
                        CryptoPassed aead -> do
                            let plaintext = BL.toStrict payload <> BS.singleton 0x02
                                (tag, ciphertext) = aeadSimpleEncrypt aead ("" :: ByteString) plaintext 16
                                body = salt
                                    <> BS.pack [0, 0, 16, 0] -- rs = 4096
                                    <> BS.singleton 65
                                    <> pointToBytes serverPublic
                                    <> ciphertext
                                    <> convert tag
                            pure (Right body)

pointFromBytes :: ByteString -> Maybe Point
pointFromBytes bytes = case BS.uncons bytes of
    Just (0x04, rest) | BS.length rest == 64 ->
        let (x, y) = BS.splitAt 32 rest
        in Just (Point (os2ip x) (os2ip y))
    _ -> Nothing

pointToBytes :: Point -> ByteString
pointToBytes (Point x y) = BS.cons 0x04 (i2osp 32 x <> i2osp 32 y)
pointToBytes PointO = BS.singleton 0

randomBytes :: Int -> IO ByteString
randomBytes = getRandomBytes

b64urlEncode :: ByteString -> Text
b64urlEncode = cs . B64URL.encodeUnpadded

b64urlDecode :: Text -> ByteString
b64urlDecode input = B64URL.decodeLenient (cs padded)
    where
        padded = input <> cs (replicate padding '=')
        padding = (4 - Text.length input `mod` 4) `mod` 4

os2ip :: ByteString -> Integer
os2ip = BS.foldl' (\acc byte -> acc `shiftL` 8 + fromIntegral byte) 0

i2osp :: Int -> Integer -> ByteString
i2osp len n = BS.pack [fromIntegral (n `shiftR` (8 * i)) .&. 0xff | i <- [len - 1, len - 2 .. 0]]
