set -euo pipefail

# Sandboxed smoke boot (see nix/checks.nix for the why and the env inputs).
T="$TMPDIR/halemans-smoke"
mkdir -p "$T"
export DEVENV_STATE="$T/state"
export DEVENV_ROOT="$T/work"   # empty: no Config/ dir -> session key autogenerated
mkdir -p "$DEVENV_STATE" "$DEVENV_ROOT"

export PATH="$HALEMANS_PROFILE/bin:$PATH"

pids=""
cleanup() {
    rc=$?
    for p in $pids; do kill "$p" 2>/dev/null || true; done
    pg_ctl -D "$T/pgdata" stop -m immediate > /dev/null 2>&1 || true
    if [ "$rc" != 0 ]; then
        echo "=== poll_zabbix_jobs ===" >&2
        psql -h "$PGHOST" -d app -c "SELECT status, attempts_count, left(coalesce(last_error,''), 200) AS err FROM poll_zabbix_jobs ORDER BY created_at DESC LIMIT 5" >&2 || true
        echo "=== zabbix problem.get ===" >&2
        curl -s -H 'Content-Type: application/json' \
            -H "Authorization: Bearer $(cat "$DEVENV_STATE/zabbix/token")" \
            -d '{"jsonrpc":"2.0","method":"problem.get","params":{"output":"extend"},"id":1}' \
            "http://127.0.0.1:10080/api_jsonrpc.php" >&2 || true
        for f in zabbix-server zabbix-web app worker; do
            if [ -f "$T/$f.log" ]; then
                echo "=== tail $f.log ===" >&2
                tail -20 "$T/$f.log" >&2
            fi
        done
    fi
}
trap cleanup EXIT

# --- postgres ----------------------------------------------------------------
export PGDATA="$T/pgdata" PGHOST="$T/pghost"
mkdir -p "$PGHOST"
initdb -D "$PGDATA" --no-locale --encoding=UTF8 > /dev/null
echo "unix_socket_directories = '$PGHOST'" >> "$PGDATA/postgresql.conf"
echo "listen_addresses = ''" >> "$PGDATA/postgresql.conf"
pg_ctl -D "$PGDATA" -l "$T/pg.log" -w start
createdb -h "$PGHOST" app
export PGDATABASE=app
export DATABASE_URL="postgres:///app?host=$PGHOST"
psql -h "$PGHOST" -d app -v ON_ERROR_STOP=1 -q \
    -f "$IHP_SCHEMA" -f "$APP_SCHEMA" -f "$APP_FIXTURES"

# --- halemans tokens + webhook token rows + poller job ------------------------
halemans-ensure-tokens
# shellcheck disable=SC1091
source "$DEVENV_STATE/halemans/env.sh"
psql -h "$PGHOST" -d app -v ON_ERROR_STOP=1 -q \
    -v am_token="$HALEMANS_AM_HOOK_TOKEN" \
    -v generic_token="$HALEMANS_GENERIC_HOOK_TOKEN" <<'SQL'
INSERT INTO webhook_tokens (source_id, token)
SELECT id, :'am_token' FROM sources WHERE type = 'alertmanager';
INSERT INTO webhook_tokens (source_id, token)
SELECT id, :'generic_token' FROM sources WHERE type = 'grafana';
-- kick the (zabbix-less here) self-rescheduling poller loop
INSERT INTO poll_zabbix_jobs DEFAULT VALUES;
INSERT INTO auto_close_jobs DEFAULT VALUES;
SQL

# Dev users + roles (milestone 1 D2): same SQL-only path as seed-halemans.
psql -h "$PGHOST" -d app -v ON_ERROR_STOP=1 -q <<'SQL'
INSERT INTO roles (name, privileges) VALUES
    ('admin',  '{view,ack,close,escalate,manage_blackouts,manage_rules,manage_users,manage_sources,admin}'),
    ('sre',    '{view,ack,close,escalate}'),
    ('viewer', '{view}');
SQL
# Passwords are hex (halemans-ensure-tokens `gen`), so colon-split is safe.
printf '%s\n' \
    "admin@dev:$HALEMANS_ADMIN_PASSWORD:admin" \
    "sre@dev:$HALEMANS_SRE_PASSWORD:sre" \
    "viewer@dev:$HALEMANS_VIEWER_PASSWORD:viewer" \
| while IFS=: read -r email pass role; do
    hash="$(halemans-hash-password "$pass")"
    psql -h "$PGHOST" -d app -v ON_ERROR_STOP=1 -q \
        -v email="$email" -v hash="$hash" -v role="$role" <<'SQL'
INSERT INTO users (email, password_hash, display_name)
VALUES (:'email', :'hash', :'email');
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u, roles r
WHERE u.email = :'email' AND r.name = :'role';
SQL
done

# --- alertmanager -------------------------------------------------------------
amcfg="$DEVENV_STATE/alertmanager"
mkdir -p "$amcfg/data"
sed "s|@HALEMANS_AM_HOOK_TOKEN@|$HALEMANS_AM_HOOK_TOKEN|g" \
    "$AM_TEMPLATE" > "$amcfg/alertmanager.yml"
alertmanager --config.file="$amcfg/alertmanager.yml" \
    --storage.path="$amcfg/data" \
    --web.listen-address=127.0.0.1:9093 \
    --cluster.listen-address="" > "$T/alertmanager.log" 2>&1 &
pids="$pids $!"

# --- grafana -------------------------------------------------------------------
mkdir -p "$DEVENV_STATE/grafana/data"
grafana server --homepath "$GRAFANA_HOME" --config "$GRAFANA_INI" \
    > "$T/grafana.log" 2>&1 &
pids="$pids $!"
for i in $(seq 1 30); do
    curl -sf "http://127.0.0.1:3001/api/health" > /dev/null 2>&1 && break
    sleep 2
done
seed-grafana

# --- zabbix (native: server + PHP web frontend + agent) --------------------------
zstate="$DEVENV_STATE/zabbix"
mkdir -p "$zstate/sock"
dbuser=$(psql -h "$PGHOST" -d postgres -tA -c "SELECT current_user")
sed -e "s|@PGHOST@|$PGHOST|g" -e "s|@PGPORT@|5432|g" \
    -e "s|@DBUSER@|$dbuser|g" -e "s|@STATE@|$zstate|g" \
    "$ZABBIX_SERVER_TEMPLATE" > "$zstate/zabbix_server.conf"
sed -e "s|@PGHOST@|$PGHOST|g" -e "s|@PGPORT@|5432|g" -e "s|@DBUSER@|$dbuser|g" \
    "$ZABBIX_WEB_TEMPLATE" > "$zstate/zabbix.conf.php"
sed -e "s|@STATE@|$zstate|g" \
    "$ZABBIX_AGENT_TEMPLATE" > "$zstate/zabbix_agentd.conf"
halemans-zabbix-db-init
"$ZABBIX_SERVER_BIN" -c "$zstate/zabbix_server.conf" -f > "$T/zabbix-server.log" 2>&1 &
pids="$pids $!"
export ZABBIX_CONFIG="$zstate/zabbix.conf.php"
"$PHP_BIN" -d memory_limit=256M -d max_execution_time=300 -d max_input_time=300 \
    -d post_max_size=16M -d date.timezone=UTC \
    -S 127.0.0.1:10080 -t "$ZABBIX_WEB_DIR" > "$T/zabbix-web.log" 2>&1 &
pids="$pids $!"
"$ZABBIX_AGENT_BIN" -c "$zstate/zabbix_agentd.conf" -f > "$T/zabbix-agent.log" 2>&1 &
pids="$pids $!"
for i in $(seq 1 30); do
    curl -sf -H 'Content-Type: application/json' \
        -d '{"jsonrpc":"2.0","method":"apiinfo.version","params":{},"id":1}' \
        "http://127.0.0.1:10080/api_jsonrpc.php" 2>/dev/null | grep -q '"result"' && break
    sleep 2
done
seed-zabbix
export ZABBIX_TOKEN="$(cat "$DEVENV_STATE/zabbix/token")"

# --- app + worker ---------------------------------------------------------------
cd "$DEVENV_ROOT"
PORT=28080 DATABASE_URL="$DATABASE_URL" "$RUN_PROD_SERVER" > "$T/app.log" 2>&1 &
pids="$pids $!"
DATABASE_URL="$DATABASE_URL" "$RUN_JOBS" > "$T/worker.log" 2>&1 &
pids="$pids $!"

export HALEMANS_APP_URL="http://127.0.0.1:28080"
for i in $(seq 1 60); do
    curl -sf "$HALEMANS_APP_URL/alerts" > /dev/null 2>&1 && break
    sleep 2
done
curl -sf "$HALEMANS_APP_URL/alerts" > /dev/null || {
    echo "app never came up; app log:" >&2
    tail -30 "$T/app.log" >&2
    exit 1
}

# --- smoke ----------------------------------------------------------------------
bash "$SMOKE_RUN"

# --- playwright (milestone 1 §10) -------------------------------------------------
export HOME="$T/home" # chromium wants a writable home in the sandbox
mkdir -p "$HOME"
python3 "$PLAYWRIGHT_SUITE"

echo "smoke check: OK" > "$out"
