set -euo pipefail

# Sandboxed smoke boot (see nix/checks.nix for the why and the env inputs).
T="$TMPDIR/halemans-smoke"
mkdir -p "$T"
export DEVENV_STATE="$T/state"
export DEVENV_ROOT="$T/work"   # empty: no Config/ dir -> session key autogenerated
mkdir -p "$DEVENV_STATE" "$DEVENV_ROOT"

export PATH="$HALEMANS_PROFILE/bin:$PATH"

pids=""
# Print the ACTUAL failures last (GitHub shows the tail of the log): the
# scenario FAIL lines from the smoke suite and playwright, plus the last
# python traceback if the playwright runner crashed outright.
failure_summary() {
    echo >&2
    echo "================ FAILURE SUMMARY ================" >&2
    if [ -f "$T/smoke.log" ]; then
        awk '/^scenario:/ { scen=$0 } /^  PASS/ { diag="" } /^  (assert-fail|timeout waiting)/ { diag=diag $0 "\n" } /^  FAIL / { if (scen != "") print scen; printf "%s", diag; diag=""; print }' "$T/smoke.log" >&2 || true
        grep -E '^smoke: [0-9]+ failure' "$T/smoke.log" >&2 || true
    fi
    if [ -f "$T/playwright.log" ]; then
        grep -E '^  FAIL ' "$T/playwright.log" >&2 || true
        if grep -q 'Traceback' "$T/playwright.log"; then
            echo "--- last playwright traceback ---" >&2
            awk '/Traceback/ { buf=""; seen=1 } seen { buf = buf $0 "\n" } END { printf "%s", buf }' "$T/playwright.log" >&2
        fi
    fi
    echo "=================================================" >&2
}
cleanup() {
    rc=$?
    for p in $pids; do kill "$p" 2>/dev/null || true; done
    pg_ctl -D "$T/pgdata" stop -m immediate > /dev/null 2>&1 || true
    if [ "$rc" != 0 ]; then
        echo "=== poll_zabbix_jobs ===" >&2
        psql -h "$PGHOST" -d halemans -c "SELECT status, attempts_count, left(coalesce(last_error,''), 200) AS err FROM poll_zabbix_jobs ORDER BY created_at DESC LIMIT 5" >&2 || true
        echo "=== zabbix problem.get ===" >&2
        curl -s -H 'Content-Type: application/json' \
            -H "Authorization: Bearer $(cat "$DEVENV_STATE/zabbix/token")" \
            -d '{"jsonrpc":"2.0","method":"problem.get","params":{"output":"extend"},"id":1}' \
            "http://127.0.0.1:10080/api_jsonrpc.php" >&2 || true
        for f in zabbix-server zabbix-web app worker mock-confluence mock-jira mock-llm mock-assets; do
            if [ -f "$T/$f.log" ]; then
                echo "=== tail $f.log ===" >&2
                tail -20 "$T/$f.log" >&2
            fi
        done
        failure_summary
    fi
}
trap cleanup EXIT

# --- postgres ----------------------------------------------------------------
export PGDATA="$T/pgdata" PGHOST="$T/pghost"
mkdir -p "$PGHOST"
initdb -D "$PGDATA" --no-locale --encoding=UTF8 > /dev/null
echo "unix_socket_directories = '$PGHOST'" >> "$PGDATA/postgresql.conf"
echo "listen_addresses = ''" >> "$PGDATA/postgresql.conf"
pg_ctl -D "$PGDATA" -l "$T/pg.log" -w start
createdb -h "$PGHOST" halemans
export PGDATABASE=halemans
export DATABASE_URL="postgres:///halemans?host=$PGHOST"
psql -h "$PGHOST" -d halemans -v ON_ERROR_STOP=1 -q \
    -f "$IHP_SCHEMA" -f "$APP_SCHEMA" -f "$APP_FIXTURES"

# --- halemans tokens + webhook token rows + poller job ------------------------
halemans-ensure-tokens
# shellcheck disable=SC1091
source "$DEVENV_STATE/halemans/env.sh"
psql -h "$PGHOST" -d halemans -v ON_ERROR_STOP=1 -q \
    -v am_token="$HALEMANS_AM_HOOK_TOKEN" \
    -v generic_token="$HALEMANS_GENERIC_HOOK_TOKEN" <<'SQL'
INSERT INTO webhook_tokens (source_id, token)
SELECT id, :'am_token' FROM sources WHERE type = 'alertmanager';
INSERT INTO webhook_tokens (source_id, token)
SELECT id, :'generic_token' FROM sources WHERE type = 'grafana';
-- kick the (zabbix-less here) self-rescheduling poller loop
INSERT INTO poll_zabbix_jobs DEFAULT VALUES;
INSERT INTO auto_close_jobs DEFAULT VALUES;
INSERT INTO poll_grafana_jobs DEFAULT VALUES;
INSERT INTO escalation_jobs DEFAULT VALUES;
INSERT INTO retention_jobs DEFAULT VALUES;
INSERT INTO source_health_jobs DEFAULT VALUES;
SQL

# Enrichment/write-back source config + integration connections + seeded
# CMDB cache row (milestone 3 D9; connections since 2.0): same SQL as
# seed-halemans (keep both in sync per project convention).
psql -h "$PGHOST" -d halemans -v ON_ERROR_STOP=1 -q <<'SQL'
UPDATE sources
SET config = config || '{"writeBack":true,"jiraWritable":true,"jiraProjects":["DEV"],"cmdbSpaces":["DEV"]}'::jsonb
WHERE type IN ('zabbix', 'grafana', 'alertmanager');

INSERT INTO jira_configs (name, base_url, token_env, api_version, projects, enabled)
SELECT 'mock-jira', 'http://127.0.0.1:18083', 'JIRA_TOKEN', '3', '["DEV"]'::jsonb, true
WHERE NOT EXISTS (SELECT 1 FROM jira_configs WHERE name = 'mock-jira');

INSERT INTO cmdb_configs (name, base_url, token_env, spaces, enabled)
SELECT 'mock-confluence', 'http://127.0.0.1:18082', 'CONFLUENCE_TOKEN', '["DEV"]'::jsonb, true
WHERE NOT EXISTS (SELECT 1 FROM cmdb_configs WHERE name = 'mock-confluence');

INSERT INTO cmdb_entries (host_id, page_id, title, excerpt, url)
SELECT h.id, '1001', 'dev-host-01',
       'Owner: team-sre. Runbook: https://wiki.example/runbooks/dev-host-01',
       '/spaces/DEV/pages/1001'
FROM hosts h
WHERE h.fqdn = 'dev-host-01'
  AND NOT EXISTS (SELECT 1 FROM cmdb_entries c WHERE c.host_id = h.id);

-- Default LLM prompt template (milestone 4 D9).
INSERT INTO llm_prompt_templates (name, version, body, active, notes)
SELECT 'alert_enrichment', 1, $tpl$You are an SRE assistant enriching an ops alert for the on-call engineer. Be concise; do not invent facts.

## Alert
- Title: {{alert.title}}
- Severity: {{alert.severity}}
- Environment: {{alert.env}}
- Host: {{alert.host}}
- Service: {{alert.service}}
- Check: {{alert.check_name}}
- Labels: {{alert.labels}}
- Annotations: {{alert.annotations}}

{{alert.description}}

## Recent events
{{events}}

## CMDB context
{{cmdb_excerpt}}

## Similar past alerts
{{similar_alerts}}

## Linked Jira tickets
{{jira_links}}

Analyze the probable cause of this alert using the context above and suggest concrete next steps for the on-call engineer.
$tpl$, true, 'seeded v1'
WHERE NOT EXISTS (SELECT 1 FROM llm_prompt_templates WHERE name = 'alert_enrichment' AND version = 1);

-- Milestone 8 D5: template v2 gains the {{assets_excerpt}} slot.
UPDATE llm_prompt_templates SET active = false, updated_at = NOW()
WHERE name = 'alert_enrichment' AND version < 2;

INSERT INTO llm_prompt_templates (name, version, body, active, notes)
SELECT 'alert_enrichment', 2, $tpl$You are an SRE assistant enriching an ops alert for the on-call engineer. Be concise; do not invent facts.

## Alert
- Title: {{alert.title}}
- Severity: {{alert.severity}}
- Environment: {{alert.env}}
- Host: {{alert.host}}
- Service: {{alert.service}}
- Check: {{alert.check_name}}
- Labels: {{alert.labels}}
- Annotations: {{alert.annotations}}

{{alert.description}}

## Recent events
{{events}}

## CMDB context
{{cmdb_excerpt}}

## Linked assets
{{assets_excerpt}}

## Similar past alerts
{{similar_alerts}}

## Linked Jira tickets
{{jira_links}}

Analyze the probable cause of this alert using the context above and suggest concrete next steps for the on-call engineer.
$tpl$, true, 'milestone 8: assets excerpt slot'
WHERE NOT EXISTS (SELECT 1 FROM llm_prompt_templates WHERE name = 'alert_enrichment' AND version = 2);

-- Assets info source pointing at the mock (milestone 8 D9) + default agent
-- role (milestone 8 D8): same as seed-halemans.
INSERT INTO assets_configs (name, base_url, token_env, auth_mode, default_schema_name, host_query_template, attribute_names, enabled)
SELECT 'assets-dev', 'http://127.0.0.1:18085/rest/assets/latest', 'ASSETS_TOKEN', 'bearer', 'Capacity CMDB',
       'objectSchema = "Capacity CMDB" AND Name like "{host}"',
       'Owner,Cluster,Database,IP,Datacenter,Service,DB Cluster,Environments,Team,Location', true
WHERE NOT EXISTS (SELECT 1 FROM assets_configs WHERE name = 'assets-dev');

-- Milestone 9 §2: passthrough facet mappings (same as seed-halemans).
INSERT INTO field_mappings (facet, rank, kind, key, enabled)
SELECT 'env', 100, 'field', 'env', true
WHERE NOT EXISTS (SELECT 1 FROM field_mappings WHERE facet = 'env' AND rank = 100);
INSERT INTO field_mappings (facet, rank, kind, key, enabled)
SELECT 'service', 100, 'field', 'service', true
WHERE NOT EXISTS (SELECT 1 FROM field_mappings WHERE facet = 'service' AND rank = 100);
INSERT INTO field_mappings (facet, rank, kind, key, enabled)
SELECT 'host', 100, 'field', 'host', true
WHERE NOT EXISTS (SELECT 1 FROM field_mappings WHERE facet = 'host' AND rank = 100);

-- Demo attr mappings for the mock CMDB matrix hosts (same as seed-halemans).
INSERT INTO field_mappings (facet, rank, kind, key, enabled)
SELECT 'Environments', 50, 'attr', 'Environments', true
WHERE NOT EXISTS (SELECT 1 FROM field_mappings WHERE facet = 'Environments' AND rank = 50);
INSERT INTO field_mappings (facet, rank, kind, key, enabled)
SELECT 'Service', 50, 'attr', 'Service', true
WHERE NOT EXISTS (SELECT 1 FROM field_mappings WHERE facet = 'Service' AND rank = 50);
INSERT INTO field_mappings (facet, rank, kind, key, enabled)
SELECT 'Location', 50, 'attr', 'Location', true
WHERE NOT EXISTS (SELECT 1 FROM field_mappings WHERE facet = 'Location' AND rank = 50);

INSERT INTO llm_agent_roles (name, description, prompt_template_name, tools, enabled, is_default)
SELECT 'default-enricher', 'Default enrichment role', 'alert_enrichment',
       '["cmdb_lookup", "jira_search", "assets_lookup"]'::jsonb, true, true
WHERE NOT EXISTS (SELECT 1 FROM llm_agent_roles WHERE name = 'default-enricher')
  AND NOT EXISTS (SELECT 1 FROM llm_agent_roles WHERE is_default);

-- Related Jira tasks filter (milestone 10 §2): same as seed-halemans.
INSERT INTO llm_prompt_templates (name, version, body, active, notes)
SELECT 'jira_related_filter', 1, $tpl$You are triaging Jira tasks related to a monitoring alert.

## Alert
- Title: {{alert.title}}
- Severity: {{alert.severity}}
- Environment: {{alert.env}}
- Host: {{alert.host}}
- Service: {{alert.service}}
- Check: {{alert.check_name}}

{{alert.description}}

## Candidate Jira tasks
{{candidates}}

You may call jira_issue_details with a task key to inspect its description and comments before deciding.
$tpl$, true, 'milestone 10: related tasks filter'
WHERE NOT EXISTS (SELECT 1 FROM llm_prompt_templates WHERE name = 'jira_related_filter' AND version = 1);

INSERT INTO llm_agent_roles (name, description, prompt_template_name, tools, enabled, is_default)
SELECT 'jira-related-filter', 'Related Jira tasks relevance filter', 'jira_related_filter',
       '["jira_issue_details"]'::jsonb, true, false
WHERE NOT EXISTS (SELECT 1 FROM llm_agent_roles WHERE name = 'jira-related-filter');

-- Default retention config (milestone 5 D10): same as seed-halemans.
INSERT INTO retention_configs (raw_events_days, enabled)
SELECT 30, true
WHERE NOT EXISTS (SELECT 1 FROM retention_configs);
SQL

# --- mock confluence + jira (milestone 3 D9) -----------------------------------
# Fixed test tokens override the random ones env.sh exported above.
export CONFLUENCE_TOKEN="test-confluence-token"
export JIRA_TOKEN="test-jira-token"
export HALEMANS_CONFLUENCE_URL="http://127.0.0.1:18082"
export HALEMANS_JIRA_URL="http://127.0.0.1:18083"
# Mock LLM (milestone 4 D9): local endpoint, no token; inherited by web/worker.
export LLM_ENDPOINT="http://127.0.0.1:18084"
export LLM_MODEL="mock-llm-1"
# Mock Assets (milestone 8 D9): fixed test token, inherited by web/worker.
export ASSETS_TOKEN="test-assets-token"
export HALEMANS_ASSETS_URL="http://127.0.0.1:18085/rest/assets/latest"
# Mock Grafana (alert metric chart): serves provisioning rule GET + ds/query
# for the lazy-load chart widget. Dedicated token env so the real grafana
# source (alert ingestion) keeps its own token.
export MOCK_GRAFANA_TOKEN="test-grafana-token"
export MOCK_GRAFANA_URL="http://127.0.0.1:18086"
# Mock Zabbix (milestone 13 metric chart): JSON-RPC trigger.get/history.get
# for the lazy-load chart widget. Dedicated token env like the grafana mock.
export MOCK_ZABBIX_TOKEN="test-zabbix-token"
export MOCK_ZABBIX_URL="http://127.0.0.1:18087"
# Flatten write-back retry backoff (1m/5m/15m) so the failure-chip smoke
# scenario reaches terminal 'failed' fast; inherited by the worker.
export HALEMANS_WRITEBACK_BACKOFF_SECONDS="0,0,0"
export HALEMANS_LLM_BACKOFF_SECONDS="0,0,0"
python3 "$MOCK_CONFLUENCE_PY" > "$T/mock-confluence.log" 2>&1 &
pids="$pids $!"
python3 "$MOCK_JIRA_PY" > "$T/mock-jira.log" 2>&1 &
pids="$pids $!"
python3 "$MOCK_LLM_PY" > "$T/mock-llm.log" 2>&1 &
pids="$pids $!"
python3 "$MOCK_ASSETS_PY" > "$T/mock-assets.log" 2>&1 &
pids="$pids $!"
python3 "$MOCK_GRAFANA_PY" > "$T/mock-grafana.log" 2>&1 &
pids="$pids $!"
python3 "$MOCK_ZABBIX_PY" > "$T/mock-zabbix.log" 2>&1 &
pids="$pids $!"
for i in $(seq 1 30); do
    curl -sf "$HALEMANS_CONFLUENCE_URL/health" > /dev/null 2>&1 \
        && curl -sf "$HALEMANS_JIRA_URL/health" > /dev/null 2>&1 \
        && curl -sf "$LLM_ENDPOINT/health" > /dev/null 2>&1 \
        && curl -sf "http://127.0.0.1:18085/health" > /dev/null 2>&1 \
        && curl -sf "$MOCK_GRAFANA_URL/health" > /dev/null 2>&1 \
        && curl -sf "$MOCK_ZABBIX_URL/health" > /dev/null 2>&1 && break
    sleep 1
done
curl -sf "$HALEMANS_CONFLUENCE_URL/health" > /dev/null \
    && curl -sf "$HALEMANS_JIRA_URL/health" > /dev/null \
    && curl -sf "$LLM_ENDPOINT/health" > /dev/null \
    && curl -sf "http://127.0.0.1:18085/health" > /dev/null \
    && curl -sf "$MOCK_GRAFANA_URL/health" > /dev/null \
    && curl -sf "$MOCK_ZABBIX_URL/health" > /dev/null || {
        echo "mocks never came up" >&2
        tail -20 "$T/mock-confluence.log" "$T/mock-jira.log" "$T/mock-llm.log" "$T/mock-assets.log" "$T/mock-grafana.log" "$T/mock-zabbix.log" >&2
        exit 1
    }

# Dev users + roles (milestone 1 D2): same SQL-only path as seed-halemans.
psql -h "$PGHOST" -d halemans -v ON_ERROR_STOP=1 -q <<'SQL'
INSERT INTO roles (name, privileges) VALUES
    ('admin',  '{view,ack,close,escalate,manage_blackouts,manage_rules,manage_users,manage_sources,admin}'),
    ('sre',    '{view,ack,close,escalate}'),
    ('viewer', '{view}');
SQL
# Passwords are hex (halemans-ensure-tokens `gen`), so colon-split is safe.
printf '%s\n' \
    "admin@dev:$HALEMANS_ADMIN_PASSWORD:admin" \
    "sre@dev:$HALEMANS_SRE_PASSWORD:sre" \
    "viewer@dev:$HALEMANS_VIEWER_PASSWORD:viewer" \
| while IFS=: read -r email pass role; do
    hash="$(halemans-hash-password "$pass")"
    psql -h "$PGHOST" -d halemans -v ON_ERROR_STOP=1 -q \
        -v email="$email" -v hash="$hash" -v role="$role" <<'SQL'
INSERT INTO users (email, password_hash, display_name)
VALUES (:'email', :'hash', :'email');
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u, roles r
WHERE u.email = :'email' AND r.name = :'role';
SQL
done

# Mock Grafana source + alert for the metric chart widget: the alert's
# generatorURL carries the mock rule uid, so the lazy-load chart fetches
# rule -> expr -> ds/query from the mock (poll disabled: no alertmanager
# listing endpoint is mocked).
psql -h "$PGHOST" -d halemans -v ON_ERROR_STOP=1 -q <<'SQL'
INSERT INTO sources (id, type, name, base_url, env, poll_interval_seconds, enabled, config) VALUES
    ('a0000000-0000-0000-0000-000000000004', 'grafana', 'grafana-mock',
     'http://127.0.0.1:18086', 'dev', 30, true,
     '{"tokenEnv":"MOCK_GRAFANA_TOKEN","metrics":{"leadMinutes":60,"trailMinutes":15,"maxPoints":500}}')
ON CONFLICT (id) DO NOTHING;
INSERT INTO alerts (fingerprint, source_id, external_id, title, severity, status, source_url, started_at)
SELECT 'grafana-mock-rule-cpu',
       'a0000000-0000-0000-0000-000000000004',
       'mock-rule-cpu',
       'Mock CPU saturation',
       'warning',
       'firing',
       'http://127.0.0.1:18086/alerting/grafana/mock-rule-cpu/view?orgId=1',
       NOW() - INTERVAL '30 minutes'
WHERE NOT EXISTS (SELECT 1 FROM alerts WHERE fingerprint = 'grafana-mock-rule-cpu');
INSERT INTO sources (id, type, name, base_url, env, poll_interval_seconds, enabled, config) VALUES
    ('a0000000-0000-0000-0000-000000000005', 'zabbix', 'zabbix-mock',
     'http://127.0.0.1:18087', 'dev', 30, false,
     '{"tokenEnv":"MOCK_ZABBIX_TOKEN","metrics":{"leadMinutes":60,"trailMinutes":15,"maxPoints":500}}')
ON CONFLICT (id) DO NOTHING;
INSERT INTO alerts (fingerprint, source_id, external_id, title, severity, status, source_url, started_at)
SELECT 'zabbix:trigger:42',
       'a0000000-0000-0000-0000-000000000005',
       '42',
       'Mock CPU load high',
       'warning',
       'firing',
       'http://127.0.0.1:18087/tr_events.php?triggerid=42&eventid=1',
       NOW() - INTERVAL '30 minutes'
WHERE NOT EXISTS (SELECT 1 FROM alerts WHERE fingerprint = 'zabbix:trigger:42');
SQL

# Milestone 9 §9: a v2-JSON dashboard exercising match + groupBy over
# materialized facets (one section per DB Cluster value). Same as
# seed-halemans.
psql -h "$PGHOST" -d halemans -v ON_ERROR_STOP=1 -q <<'SQL'
INSERT INTO dashboards (user_id, name, config, position, is_default)
SELECT id, 'DBA clusters',
       '[{"title":"PostgreSQL clusters","match":[{"facet":"attr:Service","op":"=","value":"PostgreSQL"}],"groupBy":"attr:DB Cluster","limit":50}]'::jsonb,
       50, false
FROM users WHERE email = 'sre@dev'
AND NOT EXISTS (SELECT 1 FROM dashboards WHERE name = 'DBA clusters');
SQL

# Demo dashboard for the field-mapping matrix (same as seed-halemans).
psql -h "$PGHOST" -d halemans -v ON_ERROR_STOP=1 -q <<'SQL'
INSERT INTO dashboards (user_id, name, config, position, is_default)
SELECT id, 'Service matrix', $$
[
  {"title":"ETCD / EU / PROD","match":[{"facet":"attr:Service","op":"=","value":"ETCD"},{"facet":"attr:Location","op":"=","value":"EU"},{"facet":"attr:Environments","op":"=","value":"PROD"}],"groupBy":"field:host","limit":20},
  {"title":"ETCD / EU / TEST","match":[{"facet":"attr:Service","op":"=","value":"ETCD"},{"facet":"attr:Location","op":"=","value":"EU"},{"facet":"attr:Environments","op":"=","value":"TEST"}],"groupBy":"field:host","limit":20},
  {"title":"ETCD / US / PROD","match":[{"facet":"attr:Service","op":"=","value":"ETCD"},{"facet":"attr:Location","op":"=","value":"US"},{"facet":"attr:Environments","op":"=","value":"PROD"}],"groupBy":"field:host","limit":20},
  {"title":"ETCD / US / TEST","match":[{"facet":"attr:Service","op":"=","value":"ETCD"},{"facet":"attr:Location","op":"=","value":"US"},{"facet":"attr:Environments","op":"=","value":"TEST"}],"groupBy":"field:host","limit":20},
  {"title":"POSTGRES / EU / PROD","match":[{"facet":"attr:Service","op":"=","value":"POSTGRES"},{"facet":"attr:Location","op":"=","value":"EU"},{"facet":"attr:Environments","op":"=","value":"PROD"}],"groupBy":"field:host","limit":20},
  {"title":"POSTGRES / EU / TEST","match":[{"facet":"attr:Service","op":"=","value":"POSTGRES"},{"facet":"attr:Location","op":"=","value":"EU"},{"facet":"attr:Environments","op":"=","value":"TEST"}],"groupBy":"field:host","limit":20},
  {"title":"POSTGRES / US / PROD","match":[{"facet":"attr:Service","op":"=","value":"POSTGRES"},{"facet":"attr:Location","op":"=","value":"US"},{"facet":"attr:Environments","op":"=","value":"PROD"}],"groupBy":"field:host","limit":20},
  {"title":"POSTGRES / US / TEST","match":[{"facet":"attr:Service","op":"=","value":"POSTGRES"},{"facet":"attr:Location","op":"=","value":"US"},{"facet":"attr:Environments","op":"=","value":"TEST"}],"groupBy":"field:host","limit":20}
]
$$::jsonb, 60, false
FROM users WHERE email = 'sre@dev'
AND NOT EXISTS (SELECT 1 FROM dashboards WHERE name = 'Service matrix');
SQL

# Demo API token for the smoke API/metrics assertions (milestone 6 D8): fixed
# test-only secret (the sandboxed DB is discarded after the check), both
# scopes, for sre@dev. Keep in sync with seed-halemans.
export HALEMANS_API_TOKEN="halemans-smoke-api-token-v1"
api_token_hash="$(printf %s "$HALEMANS_API_TOKEN" | sha256sum | cut -d' ' -f1)"
psql -h "$PGHOST" -d halemans -v ON_ERROR_STOP=1 -q \
    -v hash="$api_token_hash" -v prefix="${HALEMANS_API_TOKEN:0:8}" <<'SQL'
INSERT INTO api_tokens (user_id, name, token_hash, prefix, scopes)
SELECT u.id, 'smoke-cli', :'hash', :'prefix', '{alerts:read,metrics}'
FROM users u WHERE u.email = 'sre@dev';
SQL

# Teams + default routing rules (milestone 2 D4/D5): same SQL as
# seed-halemans. The default notification rule reproduces milestone-1
# dispatch: severity >= high pages the sre team, throttled to 5m.
psql -h "$PGHOST" -d halemans -v ON_ERROR_STOP=1 -q <<'SQL'
INSERT INTO teams (name, description) VALUES
    ('sre', 'Site reliability engineering');

INSERT INTO team_members (team_id, user_id, team_role)
SELECT t.id, u.id, 'lead' FROM teams t, users u
WHERE t.name = 'sre' AND u.email = 'sre@dev';

INSERT INTO team_members (team_id, user_id, team_role)
SELECT t.id, u.id, 'member' FROM teams t, users u
WHERE t.name = 'sre' AND u.email = 'admin@dev';

INSERT INTO on_call_schedules (team_id, members, rotation)
SELECT t.id, jsonb_build_array(u.id::text), '{}'
FROM teams t, users u
WHERE t.name = 'sre' AND u.email = 'sre@dev';

INSERT INTO notification_rules (position, name, enabled, match, severity_threshold, team_id, channel, channel_config, throttle_seconds)
SELECT 0, 'default-high-severity', true, '{}', 'high', t.id, 'browser_push', '{}', 300
FROM teams t WHERE t.name = 'sre';

INSERT INTO grouping_rules (position, name, enabled, version, match, group_key_template)
VALUES (0, 'env+host', true, 1, '{}', '{env}/{host}');

-- Team dashboard default (milestone 3 D7): same as seed-halemans.
UPDATE teams
SET default_dashboard_config = '[{"env":"dev","filters":{"status":[],"severity":[]}}]'::jsonb
WHERE name = 'sre';
SQL

# --- alertmanager -------------------------------------------------------------
amcfg="$DEVENV_STATE/alertmanager"
mkdir -p "$amcfg/data"
sed "s|@HALEMANS_AM_HOOK_TOKEN@|$HALEMANS_AM_HOOK_TOKEN|g" \
    "$AM_TEMPLATE" > "$amcfg/alertmanager.yml"
alertmanager --config.file="$amcfg/alertmanager.yml" \
    --storage.path="$amcfg/data" \
    --web.listen-address=127.0.0.1:9093 \
    --cluster.listen-address="" > "$T/alertmanager.log" 2>&1 &
pids="$pids $!"

# --- grafana -------------------------------------------------------------------
mkdir -p "$DEVENV_STATE/grafana/data"
grafana server --homepath "$GRAFANA_HOME" --config "$GRAFANA_INI" \
    > "$T/grafana.log" 2>&1 &
pids="$pids $!"
for i in $(seq 1 30); do
    curl -sf "http://127.0.0.1:3001/api/health" > /dev/null 2>&1 && break
    sleep 2
done
seed-grafana

# --- zabbix (native: server + PHP web frontend + agent) --------------------------
zstate="$DEVENV_STATE/zabbix"
mkdir -p "$zstate/sock"
dbuser=$(psql -h "$PGHOST" -d postgres -tA -c "SELECT current_user")
sed -e "s|@PGHOST@|$PGHOST|g" -e "s|@PGPORT@|5432|g" \
    -e "s|@DBUSER@|$dbuser|g" -e "s|@STATE@|$zstate|g" \
    "$ZABBIX_SERVER_TEMPLATE" > "$zstate/zabbix_server.conf"
sed -e "s|@PGHOST@|$PGHOST|g" -e "s|@PGPORT@|5432|g" -e "s|@DBUSER@|$dbuser|g" \
    "$ZABBIX_WEB_TEMPLATE" > "$zstate/zabbix.conf.php"
sed -e "s|@STATE@|$zstate|g" \
    "$ZABBIX_AGENT_TEMPLATE" > "$zstate/zabbix_agentd.conf"
halemans-zabbix-db-init
"$ZABBIX_SERVER_BIN" -c "$zstate/zabbix_server.conf" -f > "$T/zabbix-server.log" 2>&1 &
pids="$pids $!"
export ZABBIX_CONFIG="$zstate/zabbix.conf.php"
"$PHP_BIN" -d memory_limit=256M -d max_execution_time=300 -d max_input_time=300 \
    -d post_max_size=16M -d date.timezone=UTC \
    -S 127.0.0.1:10080 -t "$ZABBIX_WEB_DIR" > "$T/zabbix-web.log" 2>&1 &
pids="$pids $!"
"$ZABBIX_AGENT_BIN" -c "$zstate/zabbix_agentd.conf" -f > "$T/zabbix-agent.log" 2>&1 &
pids="$pids $!"
for i in $(seq 1 30); do
    curl -sf -H 'Content-Type: application/json' \
        -d '{"jsonrpc":"2.0","method":"apiinfo.version","params":{},"id":1}' \
        "http://127.0.0.1:10080/api_jsonrpc.php" 2>/dev/null | grep -q '"result"' && break
    sleep 2
done
seed-zabbix
export ZABBIX_TOKEN="$(cat "$DEVENV_STATE/zabbix/token")"
export GRAFANA_TOKEN="$(cat "$DEVENV_STATE/grafana/token")"

# --- app + worker ---------------------------------------------------------------
cd "$DEVENV_ROOT"
PORT=28080 DATABASE_URL="$DATABASE_URL" "$RUN_PROD_SERVER" > "$T/app.log" 2>&1 &
app_pid=$!
pids="$pids $app_pid"
DATABASE_URL="$DATABASE_URL" "$RUN_JOBS" > "$T/worker.log" 2>&1 &
pids="$pids $!"

# The milestone-7 provision scenario restarts the app process itself.
export SMOKE_APP_MANAGED=1
export SMOKE_APP_PID="$app_pid"
export SMOKE_APP_LOG="$T/app.log"

export HALEMANS_APP_URL="http://127.0.0.1:28080"
for i in $(seq 1 60); do
    curl -sf "$HALEMANS_APP_URL/alerts" > /dev/null 2>&1 && break
    sleep 2
done
curl -sf "$HALEMANS_APP_URL/alerts" > /dev/null || {
    echo "app never came up; app log:" >&2
    tail -30 "$T/app.log" >&2
    exit 1
}

# --- smoke ----------------------------------------------------------------------
bash "$SMOKE_RUN" 2>&1 | tee "$T/smoke.log"

# Zabbix RPC failures on the reconcile path are warn-logged and otherwise
# invisible (non-fatal by design); the scenarios above always leave tracked
# zabbix alerts, so any such line means the reconcile call itself is broken.
if grep -q "trigger-state reconcile failed" "$T/worker.log"; then
    echo "worker log shows trigger-state reconcile failures:" >&2
    grep "trigger-state reconcile failed" "$T/worker.log" | head -5 >&2
    exit 1
fi

# --- playwright (milestone 1 §10) -------------------------------------------------
export HOME="$T/home" # chromium wants a writable home in the sandbox
mkdir -p "$HOME"
python3 "$PLAYWRIGHT_SUITE" 2>&1 | tee "$T/playwright.log"

echo "smoke check: OK" > "$out"
