set -euo pipefail

# Sandboxed smoke boot (see nix/checks.nix for the why and the env inputs).
T="$TMPDIR/halemans-smoke"
mkdir -p "$T"
export DEVENV_STATE="$T/state"
export DEVENV_ROOT="$T/work"   # empty: no Config/ dir -> session key autogenerated
mkdir -p "$DEVENV_STATE" "$DEVENV_ROOT"

export PATH="$HALEMANS_PROFILE/bin:$PATH"

pids=""
cleanup() {
    for p in $pids; do kill "$p" 2>/dev/null || true; done
    pg_ctl -D "$T/pgdata" stop -m immediate > /dev/null 2>&1 || true
}
trap cleanup EXIT

# --- postgres ----------------------------------------------------------------
export PGDATA="$T/pgdata" PGHOST="$T/pghost"
mkdir -p "$PGHOST"
initdb -D "$PGDATA" --no-locale --encoding=UTF8 > /dev/null
echo "unix_socket_directories = '$PGHOST'" >> "$PGDATA/postgresql.conf"
echo "listen_addresses = ''" >> "$PGDATA/postgresql.conf"
pg_ctl -D "$PGDATA" -l "$T/pg.log" -w start
createdb -h "$PGHOST" app
export PGDATABASE=app
export DATABASE_URL="postgres:///app?host=$PGHOST"
psql -h "$PGHOST" -d app -v ON_ERROR_STOP=1 -q \
    -f "$IHP_SCHEMA" -f "$APP_SCHEMA" -f "$APP_FIXTURES"

# --- halemans tokens + webhook token rows + poller job ------------------------
halemans-ensure-tokens
# shellcheck disable=SC1091
source "$DEVENV_STATE/halemans/env.sh"
psql -h "$PGHOST" -d app -v ON_ERROR_STOP=1 -q \
    -v am_token="$HALEMANS_AM_HOOK_TOKEN" \
    -v generic_token="$HALEMANS_GENERIC_HOOK_TOKEN" <<'SQL'
INSERT INTO webhook_tokens (source_id, token)
SELECT id, :'am_token' FROM sources WHERE type = 'alertmanager';
INSERT INTO webhook_tokens (source_id, token)
SELECT id, :'generic_token' FROM sources WHERE type = 'grafana';
-- kick the (zabbix-less here) self-rescheduling poller loop
INSERT INTO poll_zabbix_jobs DEFAULT VALUES;
SQL

# --- alertmanager -------------------------------------------------------------
amcfg="$DEVENV_STATE/alertmanager"
mkdir -p "$amcfg/data"
sed "s|@HALEMANS_AM_HOOK_TOKEN@|$HALEMANS_AM_HOOK_TOKEN|g" \
    "$AM_TEMPLATE" > "$amcfg/alertmanager.yml"
alertmanager --config.file="$amcfg/alertmanager.yml" \
    --storage.path="$amcfg/data" \
    --web.listen-address=127.0.0.1:9093 \
    --cluster.listen-address="" > "$T/alertmanager.log" 2>&1 &
pids="$pids $!"

# --- grafana -------------------------------------------------------------------
mkdir -p "$DEVENV_STATE/grafana/data"
grafana server --homepath "$GRAFANA_HOME" --config "$GRAFANA_INI" \
    > "$T/grafana.log" 2>&1 &
pids="$pids $!"
for i in $(seq 1 30); do
    curl -sf "http://127.0.0.1:3001/api/health" > /dev/null 2>&1 && break
    sleep 2
done
seed-grafana

# --- app + worker ---------------------------------------------------------------
cd "$DEVENV_ROOT"
PORT=28080 DATABASE_URL="$DATABASE_URL" "$RUN_PROD_SERVER" > "$T/app.log" 2>&1 &
pids="$pids $!"
DATABASE_URL="$DATABASE_URL" "$RUN_JOBS" > "$T/worker.log" 2>&1 &
pids="$pids $!"

export HALEMANS_APP_URL="http://127.0.0.1:28080"
for i in $(seq 1 60); do
    curl -sf "$HALEMANS_APP_URL/alerts" > /dev/null 2>&1 && break
    sleep 2
done
curl -sf "$HALEMANS_APP_URL/alerts" > /dev/null || {
    echo "app never came up; app log:" >&2
    tail -30 "$T/app.log" >&2
    exit 1
}

# --- smoke ----------------------------------------------------------------------
SMOKE_ZABBIX=0 bash "$SMOKE_RUN"

echo "smoke check: OK" > "$out"
